Repository tallstackui/tallstackui, pull requests merged in 2023-10, with the labels that each got.

#48 Button Loading Effect
  dist/mix-manifest.json
  dist/tallstackui.css
  resources/views/components/buttons/circle.blade.php
  resources/views/components/buttons/index.blade.php
  src/View/Components/Button/Circle.php
  src/View/Components/Button/Index.php
  src/View/Components/Button/Traits/DefaultButtonColorClasses.php
  tests/Browser/Button/Components/ButtonComponent.php
  tests/Browser/Button/IndexTest.php
Labels: feature, beta

#49 Add. `auto-resize` in Form Textarea
  dist/mix-manifest.json
  dist/tallstackui.js
  resources/js/modules/components/form/text-area.js
  resources/js/tallstackui.js
  resources/views/components/form/textarea.blade.php
  resources/views/components/wrapper/input.blade.php
  src/View/Components/Form/Textarea.php
  src/View/Components/Wrapper/Input.php
Labels: feature, beta

#52 Tabs render without array options
  dist/mix-manifest.json
  dist/tallstackui.css
  dist/tallstackui.js
  resources/js/modules/components/tabs/tabs.js
  resources/views/components/tabs/index.blade.php
  resources/views/components/tabs/items.blade.php
  src/View/Components/Tabs/Index.php
Labels: enhancement, docs

#50 Select slot config
  resources/views/components/select/searchable.blade.php
  resources/views/components/select/styled.blade.php
  resources/views/components/wrapper/select.blade.php
  src/View/Components/Wrapper/Select.php
  tests/Browser/Select/Components/Styled/StyledAfterComponent.php
  tests/Browser/Select/Components/Styled/StyledBeforeComponent.php
  tests/Browser/Select/SearchableTest.php
  tests/Browser/Select/StyledTest.php
Labels: enhancement

#53 Dropdown Component
  dist/mix-manifest.json
  dist/tallstackui.css
  resources/views/components/dropdown/index.blade.php
  resources/views/components/dropdown/items.blade.php
  resources/views/components/interactions/dialog.blade.php
  resources/views/components/interactions/toast.blade.php
  resources/views/components/tabs/index.blade.php
  resources/views/components/tabs/item.blade.php
  resources/views/components/wrapper/select.blade.php
  src/Support/Personalization.php
  src/Support/Personalizations/Components/Dropdown/Index.php
  src/Support/Personalizations/Components/Dropdown/Items.php
  src/View/Components/Dropdown/Index.php
  src/View/Components/Dropdown/Items.php
  src/config/tallstackui.php
  tests/Browser/Dropdown/Components/DropdownActionComponent.php
  tests/Browser/Dropdown/Components/DropdownIconComponent.php
  tests/Browser/Dropdown/Components/DropdownTitleComponent.php
  tests/Browser/Dropdown/IndexTest.php
  tests/Browser/Interactions/Dialog/IndexTest.php
  tests/Browser/Interactions/Toast/IndexTest.php
  tests/Browser/Select/SearchableTest.php
Labels: feature, docs

#54 Enhancements
  dist/mix-manifest.json
  dist/tallstackui.css
  dist/tallstackui.js
  resources/js/modules/components/select/helpers.js
  resources/js/modules/components/select/select-searchable.js
  resources/js/modules/components/select/select-styled.js
  resources/views/components/buttons/circle.blade.php
  resources/views/components/card.blade.php
  resources/views/components/tabs/index.blade.php
  resources/views/components/wrapper/select.blade.php
  src/View/Components/Button/Circle.php
  src/View/Components/Card.php
  src/View/Components/Tabs/Index.php
  src/View/Components/Wrapper/Select.php
Labels: bug

#58 Enhancements
  dist/mix-manifest.json
  dist/tallstackui.js
  resources/js/modules/components/select/helpers.js
  resources/js/modules/components/select/select-searchable.js
  resources/js/modules/components/select/select-styled.js
  resources/views/components/select/searchable.blade.php
  resources/views/components/select/styled.blade.php
  resources/views/components/wrapper/select.blade.php
  src/View/Components/Select/Searchable.php
  src/View/Components/Select/Styled.php
  src/View/Components/Wrapper/Select.php
  src/View/Personalizations/Providers/ColorProvider.php
  tests/Browser/Select/StyledTest.php
Labels: enhancement
