Repository tallstackui/tallstackui, pull requests merged in 2023-12, with the labels that each got.

#88 [1.x] Add Slots in Button and Icons
  src/View/Components/Badge.php
  src/View/Components/Button/Button.php
  src/View/Components/Icon.php
  src/resources/views/components/button/button.blade.php
  src/resources/views/components/icon.blade.php
Labels: enhancement, need docs

#85 [1.x] Introducing `Banner` Component
  composer.json
  dist/mix-manifest.json
  dist/tallstackui.css
  dist/tallstackui.js
  js/modules/components/banner/banner.js
  js/tallstackui.js
  src/Actions/AbstractInteraction.php
  src/Actions/Banner.php
  src/Traits/Interactions.php
  src/View/Components/Banner.php
  src/View/Personalizations/Personalization.php
  src/View/Personalizations/Providers/ColorProvider.php
  src/View/Personalizations/Support/Colors/BannerColors.php
  src/View/Personalizations/Support/ValidateComponent.php
  src/contents/config.php
  src/resources/views/components/banner.blade.php
  tests/Browser/Banner/IndexTest.php
  tests/Browser/views/components/layouts/app.blade.php
  tests/Feature/Components/Banner/IndexTest.php
Labels: feature, need docs

#90 Fix: Added attribute type in form.input
  src/resources/views/components/form/input.blade.php
Labels: enhancement

#96 [1.x] Fixing Banner Component
  dist/mix-manifest.json
  dist/tallstackui.js
  js/modules/components/banner/banner.js
  src/resources/views/components/banner.blade.php
  tests/Feature/Components/Banner/IndexTest.php
Labels: bug

#97 [1.x] Introducing Number Component
  dist/mix-manifest.json
  dist/tallstackui.css
  dist/tallstackui.js
  js/modules/components/form/number.js
  js/plugins/numberAppearanceNone.js
  js/tallstackui.js
  src/View/Components/Form/Number.php
  src/View/Personalizations/Personalization.php
  src/contents/config.php
  src/resources/views/components/form/number.blade.php
  tailwind.config.js
  tests/Browser/Form/NumberTest.php
  tests/Feature/Components/Form/NumberTest.php
Labels: feature, need docs

#99 [1.x] Add. Ability to Use Chevron Icons in Number Component
  src/View/Components/Form/Number.php
  src/resources/views/components/form/number.blade.php
Labels: enhancement

#108 [1.x] Banner Wire Enhancements
  dist/mix-manifest.json
  dist/tallstackui.css
  src/View/Components/Banner.php
  src/resources/views/components/banner.blade.php
Labels: need docs

#109 [1.x] Allowing Arbitrary Colors in Banner Component
  src/View/Components/Banner.php
  src/View/Personalizations/Support/Colors/BannerColors.php
  src/View/Personalizations/Support/ValidateComponent.php
  src/resources/views/components/banner.blade.php
  tests/Feature/Components/Banner/IndexTest.php
Labels: need docs

#114 [1.x] Introducing Toast Expandable
  src/Actions/AbstractInteraction.php
  src/Actions/Toast.php
  src/View/Components/Interaction/Toast.php
  src/contents/config.php
  src/resources/views/components/interaction/toast.blade.php
  tests/Browser/Interactions/Toast/IndexTest.php
Labels: need docs

#115 [1.x] Introducing Alert Footer Slot
  composer.json
  composer.lock
  phpstan.neon
  src/Actions/AbstractInteraction.php
  src/Actions/Banner.php
  src/Actions/Dialog.php
  src/Actions/Toast.php
  src/TallStackUi.php
  src/View/Components/Alert.php
  src/View/Personalizations/Contracts/PersonalizableResources.php
  src/View/Personalizations/Personalization.php
  src/View/Personalizations/PersonalizationResources.php
  src/resources/views/components/alert.blade.php
  tests/Feature/Components/Alert/IndexTest.php
Labels: need docs

#126 [1.x] Introducing Input Range Component
  composer.lock
  dist/.vite/manifest.json
  dist/tallstackui-5DOS9LYp.css
  dist/tallstackui-Ks3_HpDB.css
  src/View/Components/Form/Range.php
  src/View/Personalizations/Personalization.php
  src/View/Personalizations/Providers/ColorProvider.php
  src/View/Personalizations/Support/Colors/RangeColors.php
  src/contents/config.php
  src/resources/views/components/form/range.blade.php
  src/resources/views/components/wrapper/input.blade.php
  tests/Browser/Form/RangeTest.php
  tests/Feature/Components/Form/RangeTest.php
Labels: feature, need docs

#131 [1.x] Refactoring `AbstractInteraction` Class
  src/Actions/AbstractInteraction.php
  src/Actions/Banner.php
  src/Actions/Dialog.php
  src/Actions/Toast.php
  src/Actions/Traits/InteractWithConfirmation.php
  tests/Browser/Interactions/Banner/IndexTest.php
  tests/Browser/Interactions/Toast/IndexTest.php
  tests/Feature/Structure/AbstractInteractionTest.php
Labels: enhancement

#134 [1.x] Fixing Default Label Alignment
  src/View/Components/Form/Checkbox.php
  src/View/Components/Form/Radio.php
  src/View/Components/Form/Toggle.php
  src/View/Components/Form/Traits/SetupRadioCheckboxToggle.php
  src/View/Components/Wrapper/Radio.php
  src/View/Personalizations/Support/ValidateComponent.php
  src/resources/views/components/form/checkbox.blade.php
  src/resources/views/components/form/radio.blade.php
  src/resources/views/components/form/toggle.blade.php
  src/resources/views/components/wrapper/radio.blade.php
Labels: bug

#142 [1.x] Fixing Input Password Icon Position
  src/resources/views/components/form/password.blade.php
Labels: bug

#143 [1.x] Fixing Input Wrapper
  composer.lock
  src/resources/views/components/form/password.blade.php
  src/resources/views/components/wrapper/input.blade.php
  tests/Feature/Components/Form/LabelTest.php
Labels: bug

#150 [1.x] Introducing Color Picker Component
  dist/.vite/manifest.json
  dist/tallstackui-On7gxp2o.js
  dist/tallstackui-TN_mOmlw.js
  dist/tallstackui-_02D0XEm.css
  dist/tallstackui-hCkz8sQa.css
  js/components/form/color.js
  js/tallstackui.js
  src/View/Components/Form/Color.php
  src/View/Personalizations/Personalization.php
  src/contents/config.php
  src/resources/views/components/form/color.blade.php
  tests/Browser/Form/ColorTest.php
  tests/Feature/Components/Form/ColorTest.php
Labels: feature, need docs

#160 [1.x] Refactoring Soft Personalization Usage
  composer.json
  src/Foundation/Support/BladeSupport.php
  src/View/Components/BaseComponent.php
  src/View/Components/Form/Hint.php
  src/View/Components/Wrapper/Input.php
  src/helpers.php
  src/resources/views/components/alert.blade.php
  src/resources/views/components/avatar.blade.php
  src/resources/views/components/badge.blade.php
  src/resources/views/components/banner.blade.php
  src/resources/views/components/button/button.blade.php
  src/resources/views/components/button/circle.blade.php
  src/resources/views/components/card.blade.php
  src/resources/views/components/dropdown/dropdown.blade.php
  src/resources/views/components/dropdown/items.blade.php
  src/resources/views/components/errors.blade.php
  src/resources/views/components/form/checkbox.blade.php
  src/resources/views/components/form/color.blade.php
  src/resources/views/components/form/error.blade.php
  src/resources/views/components/form/hint.blade.php
  src/resources/views/components/form/input.blade.php
  src/resources/views/components/form/label.blade.php
  src/resources/views/components/form/number.blade.php
  src/resources/views/components/form/password.blade.php
  src/resources/views/components/form/radio.blade.php
  src/resources/views/components/form/range.blade.php
  src/resources/views/components/form/textarea.blade.php
  src/resources/views/components/form/toggle.blade.php
  src/resources/views/components/interaction/dialog.blade.php
  src/resources/views/components/interaction/toast.blade.php
  src/resources/views/components/loading.blade.php
  src/resources/views/components/modal.blade.php
  src/resources/views/components/select/native.blade.php
  src/resources/views/components/select/styled.blade.php
  src/resources/views/components/slide.blade.php
  src/resources/views/components/tab/items.blade.php
  src/resources/views/components/tab/tab.blade.php
  src/resources/views/components/tooltip.blade.php
  src/resources/views/components/wrapper/input.blade.php
  src/resources/views/components/wrapper/radio.blade.php
  testbench.yaml
  tests/Feature/Structure/BaseComponentTest.php
  tests/Feature/Support/PersonalizationTest.php
Labels: enhancement

#162 [1.x] Introducing `invalidate` Parameter to Prevent Validation Error Messages
  src/Foundation/Personalization/PersonalizationResources.php
  src/View/Components/Form/Checkbox.php
  src/View/Components/Form/Color.php
  src/View/Components/Form/Input.php
  src/View/Components/Form/Label.php
  src/View/Components/Form/Number.php
  src/View/Components/Form/Password.php
  src/View/Components/Form/Radio.php
  src/View/Components/Form/Range.php
  src/View/Components/Form/Textarea.php
  src/View/Components/Form/Toggle.php
  src/View/Components/Select/Native.php
  src/View/Components/Select/Styled.php
  src/View/Components/Wrapper/Input.php
  src/View/Components/Wrapper/Radio.php
  src/resources/views/components/form/checkbox.blade.php
  src/resources/views/components/form/color.blade.php
  src/resources/views/components/form/input.blade.php
  src/resources/views/components/form/label.blade.php
  src/resources/views/components/form/number.blade.php
  src/resources/views/components/form/password.blade.php
  src/resources/views/components/form/radio.blade.php
  src/resources/views/components/form/range.blade.php
  src/resources/views/components/form/textarea.blade.php
  src/resources/views/components/form/toggle.blade.php
  src/resources/views/components/select/native.blade.php
  src/resources/views/components/select/styled.blade.php
  src/resources/views/components/wrapper/input.blade.php
  src/resources/views/components/wrapper/radio.blade.php
  tests/Browser/Form/InputTest.php
Labels: feature, need docs

#163 [1.x] Introducing Pin Input Component
  dist/.vite/manifest.json
  dist/tallstackui-CoiwIO8m.css
  dist/tallstackui-SEYhgWvn.css
  dist/tallstackui-x7oSTXZk.js
  dist/tallstackui-ygQ-e-og.js
  js/components/form/pin.js
  js/tallstackui.js
  src/Foundation/Personalization/Personalization.php
  src/View/Components/Form/Pin.php
  src/View/Components/Form/Traits/DefaultInputClasses.php
  src/config.php
  src/resources/views/components/form/pin.blade.php
  tests/Browser/Form/ColorTest.php
  tests/Browser/Form/PinTest.php
  tests/Feature/Components/Form/PinTest.php
Labels: feature, need docs

#164 [1.x] Allowing Control of the Modal Position: `top` or `center`
  src/Foundation/ResolveConfiguration.php
  src/View/Components/Modal.php
  src/config.php
  src/resources/views/components/modal.blade.php
Labels: feature, need docs

#166 [1.x] Small Refactors
  src/Actions/AbstractInteraction.php
  src/Actions/Dialog.php
  src/Actions/Toast.php
  src/Actions/Traits/InteractWithConfirmation.php
  src/Foundation/Personalization/Personalization.php
  src/View/Components/BaseComponent.php
  src/View/Components/Interaction/Dialog.php
  src/View/Components/Interaction/Toast.php
  tests/Browser/Form/PinTest.php
  tests/Feature/Structure/ComponentTest.php
  tests/Feature/Structure/InteractWithConfirmationTest.php
Labels: enhancement

#167 [1.x] Introducing Link Component
  src/Actions/AbstractInteraction.php
  src/Foundation/Colors/LinkColors.php
  src/Foundation/Colors/ResolveColor.php
  src/Foundation/Personalization/Personalization.php
  src/View/Components/BaseComponent.php
  src/View/Components/Link.php
  src/config.php
  src/resources/views/components/debug/attributes.blade.php
  src/resources/views/components/link.blade.php
  tests/Feature/Components/Link/IndexTest.php
Labels: feature, need docs

#168 [1.x] Debug Mode Enhancements
  composer.lock
  dist/.vite/manifest.json
  dist/tallstackui-CT3YnvXX.css
  dist/tallstackui-Yx3XWDYa.css
  src/Foundation/Attributes/SkipDebug.php
  src/Foundation/Attributes/SoftPersonalization.php
  src/View/Components/Alert.php
  src/View/Components/Avatar.php
  src/View/Components/Badge.php
  src/View/Components/Banner.php
  src/View/Components/BaseComponent.php
  src/View/Components/Button/Button.php
  src/View/Components/Button/Circle.php
  src/View/Components/Card.php
  src/View/Components/Dropdown/Dropdown.php
  src/View/Components/Dropdown/Items.php
  src/View/Components/Errors.php
  src/View/Components/Form/Checkbox.php
  src/View/Components/Form/Color.php
  src/View/Components/Form/Error.php
  src/View/Components/Form/Hint.php
  src/View/Components/Form/Input.php
  src/View/Components/Form/Label.php
  src/View/Components/Form/Number.php
  src/View/Components/Form/Password.php
  src/View/Components/Form/Pin.php
  src/View/Components/Form/Radio.php
  src/View/Components/Form/Range.php
  src/View/Components/Form/Textarea.php
  src/View/Components/Form/Toggle.php
  src/View/Components/Icon.php
  src/View/Components/Interaction/Dialog.php
  src/View/Components/Interaction/Toast.php
  src/View/Components/Link.php
  src/View/Components/Loading.php
  src/View/Components/Modal.php
  src/View/Components/Select/Native.php
  src/View/Components/Select/Styled.php
  src/View/Components/Slide.php
  src/View/Components/Tab/Items.php
  src/View/Components/Tab/Tab.php
  src/View/Components/Tooltip.php
  src/View/Components/Wrapper/Input.php
  src/View/Components/Wrapper/Radio.php
  src/helpers.php
  src/resources/views/components/debug/attributes.blade.php
  src/resources/views/components/link.blade.php
  tests/Feature/Structure/SoftPersonalizationAttributeTest.php
Labels: enhancement, need docs

#177 [1.x] Fixing Alert Close Icon Position
  src/View/Components/Alert.php
Labels: bug

#179 [1.x] Fixing Issue With Inputs and Masks
  src/View/Components/BaseComponent.php
  src/View/Components/Form/Checkbox.php
  src/View/Components/Form/Color.php
  src/View/Components/Form/Input.php
  src/View/Components/Form/Label.php
  src/View/Components/Form/Number.php
  src/View/Components/Form/Password.php
  src/View/Components/Form/Radio.php
  src/View/Components/Form/Range.php
  src/View/Components/Form/Textarea.php
  src/View/Components/Form/Toggle.php
  src/View/Components/Form/Traits/DetermineInputId.php
  src/View/Components/Form/Traits/SetupRadioCheckboxToggle.php
  src/resources/views/components/form/checkbox.blade.php
  src/resources/views/components/form/color.blade.php
  src/resources/views/components/form/input.blade.php
  src/resources/views/components/form/label.blade.php
  src/resources/views/components/form/number.blade.php
  src/resources/views/components/form/password.blade.php
  src/resources/views/components/form/radio.blade.php
  src/resources/views/components/form/range.blade.php
  src/resources/views/components/form/textarea.blade.php
  src/resources/views/components/form/toggle.blade.php
  src/resources/views/components/wrapper/input.blade.php
  tests/Feature/Structure/DetermineInputIdTest.php
Labels: bug

#180 [1.x] Focus the Pin to First Input When Clear
  dist/.vite/manifest.json
  dist/tallstackui-2MGmDNpm.js
  dist/tallstackui-ksW_oSJh.js
  js/components/form/pin.js
Labels: enhancement

#181 [1.x] Personalizing Dialog and Toast Button Colors
  dist/.vite/manifest.json
  dist/tallstackui-25iOt3WN.js
  dist/tallstackui-2MGmDNpm.js
  js/components/dialog/dialog.js
  src/Foundation/Colors/DialogColors.php
  src/Foundation/Colors/ResolveColor.php
  src/Foundation/Colors/ToastColors.php
  src/Foundation/Colors/Traits/OverrideColors.php
  src/resources/views/components/interaction/dialog.blade.php
  src/resources/views/components/interaction/toast.blade.php
Labels: enhancement, need docs

#184 [1.x] Allowing Dark Theme Helper Initialize `darkTheme` Variable as `true`
  dist/.vite/manifest.json
  dist/tallstackui-25iOt3WN.js
  dist/tallstackui-zGB4kDaf.js
  js/helpers/dark-theme.js
Labels: enhancement, need docs

#182 [1.x] Allowing the Usage of Duplicated `label` in Select Component
  src/resources/views/components/select/styled.blade.php
  tests/Browser/Select/StyledCommonTest.php
Labels: enhancement

#186 [1.x] Adapting Components to Work Without Livewire
  dist/.vite/manifest.json
  dist/tallstackui-i83irOb8.js
  dist/tallstackui-zGB4kDaf.js
  js/components/form/color.js
  js/components/form/pin.js
  js/components/select/select.js
  src/Facades/TallStackUi.php
  src/Foundation/Colors/DialogColors.php
  src/Foundation/Support/BladeBindProperty.php
  src/Foundation/Support/BladeDirectives.php
  src/Foundation/Support/BladeSupport.php
  src/TallStackUi.php
  src/View/Components/BaseComponent.php
  src/View/Components/Form/Error.php
  src/View/Components/Form/Traits/DetermineInputId.php
  src/View/Components/Select/Styled.php
  src/View/Components/Wrapper/Input.php
  src/View/Components/Wrapper/Radio.php
  src/resources/views/components/debug/attributes.blade.php
  src/resources/views/components/form/checkbox.blade.php
  src/resources/views/components/form/color.blade.php
  src/resources/views/components/form/error.blade.php
  src/resources/views/components/form/input.blade.php
  src/resources/views/components/form/number.blade.php
  src/resources/views/components/form/password.blade.php
  src/resources/views/components/form/pin.blade.php
  src/resources/views/components/form/radio.blade.php
  src/resources/views/components/form/range.blade.php
  src/resources/views/components/form/textarea.blade.php
  src/resources/views/components/form/toggle.blade.php
  src/resources/views/components/select/native.blade.php
  src/resources/views/components/select/styled.blade.php
  src/resources/views/components/tab/tab.blade.php
  src/resources/views/components/wrapper/input.blade.php
  src/resources/views/components/wrapper/radio.blade.php
Labels: feature, need docs

#188 [1.x] Dispatching Interactions (Dialog & Toast) Through JavaScript
  dist/.vite/manifest.json
  dist/tallstackui-0VaCpNGV.js
  dist/tallstackui-VMjdLlI3.js
  js/components/dialog/dialog.js
  js/components/loading/loading.js
  js/components/toast/toast-loop.js
  js/globals/globals.js
  js/globals/interactions/confirmation.js
  js/globals/interactions/dialog.js
  js/globals/interactions/toast.js
  js/helpers.js
  src/resources/views/components/interaction/dialog.blade.php
  src/resources/views/components/interaction/toast.blade.php
  tests/Browser/Interactions/Dialog/IndexTest.php
  tests/Browser/Interactions/Toast/IndexTest.php
Labels: feature, need docs

#189 [1.x] Introducing Component Events
  dist/.vite/manifest.json
  dist/tallstackui-LJ40NPXL.js
  dist/tallstackui-QL41L2Zj.js
  js/components/dialog/dialog.js
  js/components/modal/modal.js
  js/components/slide/slide.js
  js/components/toast/toast-loop.js
  js/globals/globals.js
  js/helpers.js
  src/resources/views/components/modal.blade.php
  src/resources/views/components/slide.blade.php
  tests/Browser/Interactions/Dialog/IndexTest.php
  tests/Browser/Interactions/Toast/IndexTest.php
  tests/Browser/Modal/IndexTest.php
  tests/Browser/Slide/IndexTest.php
Labels: feature, need docs

#191 [1.x] Introducing Table Component
  dist/.vite/manifest.json
  dist/tallstackui-9EYB9KlE.css
  dist/tallstackui-Ac1daJLi.css
  src/Foundation/Personalization/Personalization.php
  src/Foundation/Support/BladeDirectives.php
  src/View/Components/BaseComponent.php
  src/View/Components/Table.php
  src/config.php
  src/lang/en/messages.php
  src/lang/es/messages.php
  src/lang/fr/messages.php
  src/lang/km/messages.php
  src/lang/pt/messages.php
  src/lang/pt_BR/messages.php
  src/lang/tr/messages.php
  src/resources/views/components/debug/attributes.blade.php
  src/resources/views/components/table/index.blade.php
  src/resources/views/components/table/paginators.blade.php
  tests/Browser/Table/IndexTest.php
  tests/Feature/Components/Table/IndexTest.php
Labels: feature, need docs

#196 [1.x] Support for `wire:change` in Some Components
  dist/.vite/manifest.json
  dist/tallstackui--aIjrDPM.css
  dist/tallstackui-KTpMLjR3.js
  dist/tallstackui-QZ4hmj8L.css
  dist/tallstackui-RH0XMt05.js
  js/components/form/color.js
  js/components/form/number.js
  js/components/form/pin.js
  js/components/select/select.js
  js/helpers.js
  src/Foundation/Traits/LivewireChangeEvent.php
  src/View/Components/Form/Pin.php
  src/View/Components/Select/Styled.php
  src/resources/views/components/form/pin.blade.php
  src/resources/views/components/select/styled.blade.php
  tests/Browser/Form/ColorTest.php
  tests/Browser/Form/NumberTest.php
  tests/Browser/Form/PinTest.php
  tests/Browser/Select/StyledCommonTest.php
Labels: feature

#197 [1.x] Introducing Clipboard Component
  dist/.vite/manifest.json
  dist/tallstackui--aIjrDPM.css
  dist/tallstackui-KTpMLjR3.js
  dist/tallstackui-Y34IxQvC.js
  dist/tallstackui-tPu1NTtt.css
  js/components/clipboard/clipboard.js
  js/tallstackui.js
  package-lock.json
  package.json
  src/Foundation/Personalization/Personalization.php
  src/View/Components/Clipboard.php
  src/config.php
  src/lang/en/messages.php
  src/lang/es/messages.php
  src/lang/fr/messages.php
  src/lang/km/messages.php
  src/lang/pt/messages.php
  src/lang/pt_BR/messages.php
  src/lang/tr/messages.php
  src/resources/views/components/clipboard.blade.php
  tests/Browser/Clipboard/IndexTest.php
  tests/Feature/Components/Clipboard/IndexTest.php
  tests/Feature/Datasets.php
Labels: feature, need docs

#202 [1.x] Avoid Display `cancel` Button in Dialog & Toast When Not Defined
  src/Actions/Traits/InteractWithConfirmation.php
  src/resources/views/components/interaction/dialog.blade.php
  src/resources/views/components/interaction/toast.blade.php
  tests/Browser/Interactions/Dialog/IndexTest.php
  tests/Browser/Interactions/Toast/IndexTest.php
Labels: need docs
