Repository tallstackui/tallstackui, pull requests merged in 2024-02, with the labels that each got.

#280 [1.x] Fix Input Load via Dynamic Component in `upload`
  src/resources/views/components/form/upload.blade.php
Labels: bug

#285 [1.x] Fixing Button Infinity Loading Effect Out of Livewire
  src/resources/views/components/button/button.blade.php
  src/resources/views/components/button/circle.blade.php
Labels: bug

#283 [1.x] Introduce `TimePicker` Component
  dist/.vite/manifest.json
  dist/tallstackui-1ZW6uusO.js
  dist/tallstackui-BXMfTnoM.js
  dist/tallstackui-DbPYLcHm.css
  dist/tallstackui-WktyfrGA.css
  js/components/form/timepicker.js
  js/helpers.js
  js/tallstackui.js
  src/Foundation/Personalization/Personalization.php
  src/View/Components/Form/TimePicker.php
  src/config.php
  src/lang/en/messages.php
  src/lang/es/messages.php
  src/lang/fr/messages.php
  src/lang/km/messages.php
  src/lang/pt/messages.php
  src/lang/pt_BR/messages.php
  src/lang/tr/messages.php
  src/resources/views/components/form/timepicker.blade.php
  tests/Browser/Form/TimePickerTest.php
  tests/Browser/views/components/layouts/app.blade.php
  tests/Fixtures/dayjs/dayjs.min.js
Labels: feature, need docs, summer release

#288 [1.x] Allowing Search Through Option Description of Select Styled Component
  dist/.vite/manifest.json
  dist/tallstackui-9AGzs5vk.js
  js/components/select/select.js
  tests/Browser/Select/StyledCommonTest.php
Labels: feature, summer release

#290 [1.x][Summer Release] Theme Switch Component
  dist/.vite/manifest.json
  dist/tallstackui-DbPYLcHm.css
  dist/tallstackui-ROyo0c5-.css
  src/Foundation/Personalization/Personalization.php
  src/View/Components/ThemeSwitch.php
  src/config.php
  src/resources/views/components/theme-switch.blade.php
  tailwind.config.js
Labels: feature, need docs, summer release

#294 [1.x] Fixing Dropdown With Tag A
  rector.php
  src/Foundation/Exceptions/InvalidSelectedPositionException.php
  src/View/Components/Dropdown/Dropdown.php
  src/resources/views/components/dropdown/items.blade.php
Labels: bug

#295 [1.x] Fixing Input Focus
  src/View/Components/Form/Traits/DefaultInputClasses.php
  src/resources/views/components/form/input.blade.php
Labels: bug

#298 [1.x] Input and Components Enhancements
  .gitattributes
  .gitignore
  dist/.vite/manifest.json
  dist/tallstackui-1ZW6uusO.js
  dist/tallstackui-7lDMVMnv.js
  dist/tallstackui-WktyfrGA.css
  dist/tallstackui-ja5C-0Ki.css
  js/components/form/password.js
  js/components/select/select.js
  src/View/Components/Form/Color.php
  src/View/Components/Form/Number.php
  src/View/Components/Form/Password.php
  src/View/Components/Form/Pin.php
  src/View/Components/Form/Tag.php
  src/View/Components/Form/Traits/DefaultInputClasses.php
  src/View/Components/Form/Upload.php
  src/View/Components/Select/Styled.php
  src/resources/views/components/form/color.blade.php
  src/resources/views/components/form/input.blade.php
  src/resources/views/components/form/password.blade.php
  src/resources/views/components/form/pin.blade.php
  src/resources/views/components/form/upload.blade.php
  src/resources/views/components/interaction/dialog.blade.php
  src/resources/views/components/select/styled.blade.php
  tests/Browser/Form/PasswordTest.php
  tests/Browser/Select/StyledCommonTest.php
Labels: enhancement, need docs

#303 [1.x] Fixing `Tab` Components With Livewire Components
  src/resources/views/components/tab/tab.blade.php
Labels: bugfix

#302 [1.x][Summer Release] Introduce Stats Component
  dist/.vite/manifest.json
  dist/tallstackui-Cub-H3N9.js
  dist/tallstackui-a1Xfew9v.js
  dist/tallstackui-nTWoz609.css
  dist/tallstackui-x1Jp11nz.css
  js/components/stats/stats.js
  js/tallstackui.js
  src/Foundation/Colors/ResolveColor.php
  src/Foundation/Colors/StatsColors.php
  src/Foundation/Personalization/Personalization.php
  src/Foundation/Support/Components/IconGuide.php
  src/View/Components/Stats.php
  src/config.php
  src/resources/views/components/stats.blade.php
  tests/Feature/Components/Stats/IndexTest.php
Labels: feature, need docs, summer release

#304 [1.x] Fixing `intl` Exception in Upload Component
  src/resources/views/components/form/upload.blade.php
Labels: bugfix

#310 [1.x] Prevents Usage of `Upload` Components Without `wire:model`
  src/resources/views/components/form/upload.blade.php
  tests/Browser/Form/UploadTest.php
Labels: bugfix

#312 [1.x][Summer Release] Form Step Component
  dist/.vite/manifest.json
  dist/tallstackui-B05iyxhh.js
  dist/tallstackui-BEVg6ifw.js
  dist/tallstackui-BNFowVhu.css
  dist/tallstackui-nTWoz609.css
  js/components/step/step.js
  js/tallstackui.js
  src/Foundation/Personalization/Personalization.php
  src/Foundation/Support/Components/IconGuide.php
  src/View/Components/Step/Items.php
  src/View/Components/Step/Step.php
  src/config.php
  src/lang/en/messages.php
  src/lang/es/messages.php
  src/lang/fr/messages.php
  src/lang/km/messages.php
  src/lang/pt/messages.php
  src/lang/pt_BR/messages.php
  src/lang/tr/messages.php
  src/resources/views/components/step/items.blade.php
  src/resources/views/components/step/step.blade.php
  src/resources/views/components/step/variations/circles.blade.php
  src/resources/views/components/step/variations/panels.blade.php
  src/resources/views/components/step/variations/simple.blade.php
  tests/Browser/Step/IndexTest.php
  tests/Feature/Components/Step/IndexTest.php
Labels: feature, need docs, summer release

#313 [1.x][Summer Release] Introducing Command to Easily Set Component Prefixes
  src/Foundation/Console/SetupPrefixCommand.php
  src/Foundation/Support/Blade/BladeComponentPrefix.php
  src/TallStackUiServiceProvider.php
Labels: feature, need docs, summer release

#315 TimePicker UI Enhacements
  src/View/Components/Form/TimePicker.php
  src/resources/views/components/form/timepicker.blade.php
Labels: enhancement, summer release

#318 [1.x] Fixing Upload Component Extension Error
  composer.json
  phpstan.neon
  src/Foundation/Support/Components/UploadComponentFileAdapter.php
Labels: bugfix

#320 [1.x] Add. Dutch Language
  src/lang/nl/messages.php
Labels: feature

#329 [1.x] Floating Component
  dist/.vite/manifest.json
  dist/tallstackui-Bz4TDiju.css
  dist/tallstackui-CDXsW3No.css
  src/Foundation/Personalization/Personalization.php
  src/View/Components/Floating.php
  src/View/Components/Form/DatePicker.php
  src/View/Components/Form/TimePicker.php
  src/View/Components/Select/Styled.php
  src/config.php
  src/resources/views/components/floating.blade.php
  src/resources/views/components/form/datepicker.blade.php
  src/resources/views/components/form/password.blade.php
  src/resources/views/components/form/timepicker.blade.php
  src/resources/views/components/form/upload.blade.php
  src/resources/views/components/select/styled.blade.php
  tests/Browser/Form/DatePickerTest.php
  tests/Browser/Form/UploadTest.php
Labels: need docs
