Repository tallstackui/tallstackui, pull requests merged in 2024-01, with the labels that each got.

#208 [1.x] Bugfix for Table Pagination Element & Add. `simple-pagination` Option
  src/Foundation/Support/BladeDirectives.php
  src/View/Components/Table.php
  src/resources/views/components/table/index.blade.php
  src/resources/views/components/table/paginators.blade.php
  tests/Browser/Table/IndexTest.php
Labels: bug, need docs

#213 [1.x] Sync Pin Component with External Changes
  dist/.vite/manifest.json
  dist/tallstackui-1icN5H2Q.js
  dist/tallstackui-5wMiczcT.js
  js/components/form/pin.js
  tests/Browser/Form/PinTest.php
Labels: enhancement

#216 [1.x] Introducing Scoped Personalization
  dist/.vite/manifest.json
  dist/tallstackui-U6Vs1IYR.css
  dist/tallstackui-tPu1NTtt.css
  src/Foundation/Personalization/BuildScopePersonalization.php
  src/View/Components/BaseComponent.php
  tests/Feature/Structure/BuildScopePersonalizationTest.php
  tests/Feature/Support/PersonalizationTest.php
Labels: feature, need docs

#220 [1.x] Allowing Definition of Inline-placeholder for `select.styled`
  .github/workflows/tests.yml
  src/View/Components/Select/Styled.php
  src/resources/views/components/select/styled.blade.php
  tests/Feature/Components/Select/SelectStyledTest.php
Labels: feature, need docs

#221 [1.x] Bugfix: Label Reference for Radio, Checkbox, Toggle
  src/View/Components/Form/Checkbox.php
  src/View/Components/Form/Radio.php
  src/View/Components/Form/Toggle.php
  src/resources/views/components/form/checkbox.blade.php
  src/resources/views/components/form/radio.blade.php
  src/resources/views/components/form/toggle.blade.php
Labels: bug

#222 [1.x] Introducing Dialog `dismissed` Event.
  dist/.vite/manifest.json
  dist/tallstackui-fD-8J8_0.js
  dist/tallstackui-xyX3uHve.js
  js/components/dialog/dialog.js
  src/resources/views/components/interaction/dialog.blade.php
  tests/Browser/Interactions/Dialog/IndexTest.php
Labels: feature, need docs

#225 [1.x] Introducing `select.styled` Required Property
  dist/.vite/manifest.json
  dist/tallstackui-_Tz5omC5.js
  dist/tallstackui-xyX3uHve.js
  js/components/select/select.js
  src/View/Components/Select/Styled.php
  src/resources/views/components/select/styled.blade.php
  tests/Browser/Select/StyledCommonTest.php
Labels: feature, need docs

#232 [1.x] Introducing Tag Component
  dist/.vite/manifest.json
  dist/tallstackui-9nEhfeN0.js
  dist/tallstackui-FQzjZze6.css
  dist/tallstackui-vWc0bNL4.css
  dist/tallstackui-wdvue7LI.js
  js/components/form/tag.js
  js/tallstackui.js
  src/Foundation/Personalization/Personalization.php
  src/Foundation/Traits/SanitizePropertyValue.php
  src/View/Components/Form/Tag.php
  src/View/Components/Select/Styled.php
  src/config.php
  src/resources/views/components/form/tag.blade.php
  src/resources/views/components/select/styled.blade.php
  tests/Browser/Form/TagTest.php
  tests/Feature/Components/Form/ColorTest.php
  tests/Feature/Components/Form/InputTest.php
  tests/Feature/Components/Form/TagTest.php
Labels: feature, need docs

#242 [1.x] Introducing Password Rules Validation
  captainhook.json
  dist/.vite/manifest.json
  dist/tallstackui-1uS1OmhT.js
  dist/tallstackui-afP4X2cm.css
  dist/tallstackui-dJ_9gOmH.js
  dist/tallstackui-umiujDdA.css
  js/components/form/password.js
  js/tallstackui.js
  src/View/Components/Form/Password.php
  src/lang/en/messages.php
  src/lang/es/messages.php
  src/lang/fr/messages.php
  src/lang/km/messages.php
  src/lang/pt/messages.php
  src/lang/pt_BR/messages.php
  src/lang/tr/messages.php
  src/resources/views/components/form/password.blade.php
  tests/Feature/Components/Form/PasswordTest.php
Labels: feature, need docs

#243 [1.x] Password: Introducing Password Generator
  dist/.vite/manifest.json
  dist/tallstackui-1uS1OmhT.js
  dist/tallstackui-GPx_x83h.js
  js/components/form/password.js
  src/View/Components/Form/Password.php
  src/resources/views/components/form/password.blade.php
  tests/Feature/Components/Form/PasswordTest.php
Labels: feature, need docs

#249 [1.x] Fixing Dropdown Component with Livewire SPA Mode
  dist/.vite/manifest.json
  dist/tallstackui-GPx_x83h.js
  dist/tallstackui-Ot6N-ODA.js
  js/components/dropdown/dropdown.js
Labels: bug

#252 [1.x] Bugfix & Event Addition for Tag Component
  dist/.vite/manifest.json
  dist/tallstackui-Ot6N-ODA.js
  dist/tallstackui-SQyMVmBw.js
  js/components/form/tag.js
  package-lock.json
  package.json
  src/View/Components/Form/Tag.php
  src/resources/views/components/form/tag.blade.php
  tests/Browser/Form/TagTest.php
  tests/Browser/Form/tests/Browser/console/.gitignore
  tests/Browser/Form/tests/Browser/screenshots/.gitignore
  tests/Browser/Form/tests/Browser/source/.gitignore
Labels: bug, feature, need docs

#251 [1.x] Number component centralized
  dist/.vite/manifest.json
  dist/tallstackui-rBYMb5gb.css
  dist/tallstackui-z4anvJqz.css
  src/View/Components/Form/Number.php
  src/resources/views/components/form/number.blade.php
Labels: enhancement, need docs

#254 [1.x] Errors Component: Add slot footer
  src/View/Components/Errors.php
  src/resources/views/components/errors.blade.php
Labels: enhancement, need docs

#255 [1.x] Clipboard component: Add `copy` Event
  .gitignore
  composer.lock
  dist/.vite/manifest.json
  dist/tallstackui-SQyMVmBw.js
  dist/tallstackui-fGf9EGdb.js
  js/components/clipboard/clipboard.js
  src/resources/views/components/clipboard.blade.php
  tests/Browser/Clipboard/IndexTest.php
Labels: feature, need docs

#259 [1.x] Select component: Added more customization blocks
  dist/.vite/manifest.json
  dist/tallstackui-PA0XaKX5.css
  dist/tallstackui-azfDbqpn.css
  src/View/Components/Select/Styled.php
  src/resources/views/components/select/styled.blade.php
Labels: enhancement

#260 [1.x] Introducing Reaction Component
  dist/.vite/manifest.json
  dist/tallstackui-LBsTVDb2.js
  dist/tallstackui-PA0XaKX5.css
  dist/tallstackui-Z_-hBmIH.js
  dist/tallstackui-rBuqcJJZ.css
  js/components/reaction/reaction.js
  js/tallstackui.js
  src/Foundation/Exceptions/InvalidSelectedPositionException.php
  src/Foundation/Exceptions/MissingLivewireException.php
  src/Foundation/Personalization/Personalization.php
  src/View/Components/Reaction.php
  src/View/Components/Tooltip.php
  src/config.php
  src/resources/views/components/form/upload.blade.php
  src/resources/views/components/reaction.blade.php
  tests/Browser/Reaction/IndexTest.php
Labels: feature, need docs

#267 [1.x] Add JS Events in All Supported Components
  composer.lock
  dist/.vite/manifest.json
  dist/tallstackui-1ZW6uusO.js
  dist/tallstackui-GZ9LzdE3.js
  js/components/form/color.js
  js/components/select/select.js
  src/View/Components/Wrapper/Input.php
  src/resources/views/components/errors.blade.php
  src/resources/views/components/form/color.blade.php
  src/resources/views/components/form/password.blade.php
  src/resources/views/components/select/styled.blade.php
  src/resources/views/components/wrapper/input.blade.php
  tests/Browser/Errors/IndexTest.php
  tests/Browser/Form/ColorTest.php
  tests/Browser/Form/PasswordTest.php
  tests/Browser/Select/StyledCommonTest.php
Labels: feature, need docs

#278 [1.x] Add. Default Toast Timeout
  src/Actions/Toast.php
  src/config.php
Labels: enhancement, need docs
