Repository tallstackui/tallstackui, pull requests merged in 2024-03, with the labels that each got.

#331 [1.x][Summer Release] Floating Enhancements
  dist/.vite/manifest.json
  dist/tallstackui-BfmdK-yY.css
  dist/tallstackui-TyZpO-fa.css
  src/View/Components/Dropdown/Dropdown.php
  src/View/Components/Floating.php
  src/View/Components/Form/Color.php
  src/View/Components/Form/Password.php
  src/View/Components/Form/Upload.php
  src/View/Components/Select/Styled.php
  src/resources/views/components/dropdown/dropdown.blade.php
  src/resources/views/components/floating.blade.php
  src/resources/views/components/form/color.blade.php
  src/resources/views/components/form/date.blade.php
  src/resources/views/components/form/password.blade.php
  src/resources/views/components/form/time.blade.php
  src/resources/views/components/form/upload.blade.php
  src/resources/views/components/select/styled.blade.php
Labels: summer release

#341 [1.x] [Summer Release] Step Parse Integer Selected Value
  src/resources/views/components/step/items.blade.php
  src/resources/views/components/step/variations/circles.blade.php
  src/resources/views/components/step/variations/panels.blade.php
  src/resources/views/components/step/variations/simple.blade.php
Labels: enhancement, summer release

#355 [1.x] Setup Prefix Using Env
  src/Foundation/Console/SetupPrefixCommand.php
  src/View/Components/Select/Styled.php
  src/config.php
Labels: need docs

#366 [1.x] [Feature] Progress Component
  dist/.vite/manifest.json
  dist/tallstackui-BMCmEjw7.css
  dist/tallstackui-Z_3UG_Gk.css
  src/Foundation/Colors/ProgressColors.php
  src/Foundation/Colors/ResolveColor.php
  src/Foundation/Personalization/Personalization.php
  src/View/Components/Progress/Circle.php
  src/View/Components/Progress/Progress.php
  src/config.php
  src/resources/views/components/progress/circle.blade.php
  src/resources/views/components/progress/progress.blade.php
  src/resources/views/components/progress/variations/floating.blade.php
  src/resources/views/components/progress/variations/simple.blade.php
  src/resources/views/components/progress/variations/title.blade.php
  tests/Feature/Components/Progress/IndexTest.php
Labels: feature, need docs

#378 [1.x] Fixing Date Min & Max Time & Reopening Floating With Correct Calendar
  dist/.vite/manifest.json
  dist/tallstackui-DON8s8-D.js
  dist/tallstackui-DgupOrQ5.js
  js/components/form/date.js
  src/View/Components/Form/Date.php
  tests/Browser/Form/DateTest.php
Labels: bugfix

#380 [1.x] Enhancements on Table
  src/View/Components/Table.php
  src/resources/views/components/table/index.blade.php
Labels: enhancement, need docs, breaking change

#381 [1.x] Fixing Select `x-for` Key
  src/View/Components/Select/Styled.php
  src/resources/views/components/select/styled.blade.php
Labels: bugfix

#382 [1.x] Fixing Date Component Issues
  dist/.vite/manifest.json
  dist/tallstackui-BDTKHEnq.css
  dist/tallstackui-By5Zh4y6.js
  dist/tallstackui-DON8s8-D.js
  dist/tallstackui-DS18YEXa.css
  js/components/form/date.js
  src/View/Components/Form/Date.php
  src/resources/views/components/form/date.blade.php
  tests/Browser/Form/DateTest.php
Labels: bugfix
